# All available wildcards
years:
  - "2015"
  - "2016"
  - "2017"
  - "2018"

polarities:
  - mu
  - md

mc_modes:
  - B2DDpi
  - B2DpDstmpi
  - B2D0D0pi2b2b
  - B2D0D0pi2b4b
  - B2DstpDmpi
  - B2DstDstpi

data_modes:
  - B2DdDdPi
  - B2D0D0Pi2b4b
  - B2D0D0Pi2b2b
  - B2DstDdPi4b
  - B2DstDdPi2b
  - B2DstDstPi2b2b

misID_modes:
  - B2DDK
  - B2D0D0bK

massfit_modes:
  - B2DDpi
  - B2D0D0pi2b2b
  - B2D0D0pi2b4b


working_points_BDT:
    "B2DDpi": 0.12
    "B2D0D0pi2b2b": 0.08
    "B2D0D0pi2b4b": 0.15
    "B2DpDstmpi": 0.2
    "B2DstpDmpi": 0.2
    "B2DstDstpi": -9999 
