configfile: "config.yaml"


include: "helpers.smk"


"""
Set of rules to produce ntuples for B+ -> D Dbar pi+ analysis.
Available wildcards are defined in config.yaml
"""


wildcard_constraints:
    year="\d{4}",


# rule help:
#    """
#    Print list of all targets with help.
#    """
#    run:
#        for rule in workflow.rules:
#            print(rule.name)
#            print(rule.docstring)


workpath = os.path.dirname(workflow.snakefile)


"""
rule all:
    input:
        #expand(rules.apply_preselection_MC.output.files, mode=mc_modes, year=years, mag=config["polarities"]),
        expand(rules.apply_preselection_data.output.files, mode=config["data_modes"], year=config["years"], mag=config["polarities"]),
"""


include: "MC/Snakefile"
include: "data/Snakefile"
include: "mva/Snakefile"
include: "misID/Snakefile"
include: "massfit/Snakefile"
include: "checks/Snakefile"


rule all:
    input:
        #expand(rules.merge_data.output.files, mode=config["massfit_modes"]),
        #expand(rules.merge_MC.output.files, mode=config["massfit_modes"]),
        expand(rules.draw_fom_curve.output.files, mode=config["massfit_modes"]),
        expand(rules.plot_misID_shape.output.files, misid_mode=config["misID_modes"]),
        expand(rules.fit_data_sw.output.files, mode=config["massfit_modes"]),
