configfile: "config.yaml"


include: "helpers.smk"


"""
Set of rules to produce ntuples for B+ -> D Dbar pi+ analysis.
Available wildcards are defined in config.yaml
"""


wildcard_constraints:
    year="\d{4}",


# rule help:
#    """
#    Print list of all targets with help.
#    """
#    run:
#        for rule in workflow.rules:
#            print(rule.name)
#            print(rule.docstring)


workpath = os.path.dirname(workflow.snakefile)

# data_modes=["B2DdDdPi","B2D0D0Pi2b2b","B2D0D0Pi2b4b"]
data_modes = ["B2DstDdPi2b"]
years = ["2015"]
mc_modes = ["B2DDpi-sqDalitz"]

"""
rule all:
    input:
        #expand(rules.apply_preselection_MC.output.files, mode=mc_modes, year=years, mag=config["polarities"]),
        expand(rules.apply_preselection_data.output.files, mode=config["data_modes"], year=config["years"], mag=config["polarities"]),
"""


include: "MC/Snakefile"
include: "data/Snakefile"
include: "mva/Snakefile"


rule all:
    input:
        #expand(rules.merge_data.output.files, mode=config["mc_modes"]),
        #expand(rules.merge_MC.output.files, mode=config["mc_modes"]),
        expand(rules.draw_fom_curve.output.files, mode=config["mc_modes"]),
