/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOCRUIJFFPDF
#define ROOCRUIJFFPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooCruijffPdf : public RooAbsPdf {
public:
  RooCruijffPdf() {} ; 
  RooCruijffPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _m0,
	      RooAbsReal& _sigmaL,
	      RooAbsReal& _sigmaR,
	      RooAbsReal& _alphaL,
	      RooAbsReal& _alphaR);
  RooCruijffPdf(const RooCruijffPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooCruijffPdf(*this,newname); }
  inline virtual ~RooCruijffPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy m0 ;
  RooRealProxy sigmaL ;
  RooRealProxy sigmaR ;
  RooRealProxy alphaL ;
  RooRealProxy alphaR ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooCruijffPdf,1) // Your description goes here...
};
 
#endif
