/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOEXTENDEDCRUIJFFPDF
#define ROOEXTENDEDCRUIJFFPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooExtendedCruijffPdf : public RooAbsPdf {
public:
  RooExtendedCruijffPdf() {} ; 
  RooExtendedCruijffPdf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _m0,
	      RooAbsReal& _sigma,
	      RooAbsReal& _alphaL,
	      RooAbsReal& _alphaR,
	      RooAbsReal& _beta);
  RooExtendedCruijffPdf(const RooExtendedCruijffPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooExtendedCruijffPdf(*this,newname); }
  inline virtual ~RooExtendedCruijffPdf() { }

protected:

  RooRealProxy x ;
  RooRealProxy m0 ;
  RooRealProxy sigma ;
  RooRealProxy alphaL ;
  RooRealProxy alphaR ;
  RooRealProxy beta ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooExtendedCruijffPdf,1) // Your description goes here...
};
 
#endif
