B2D0D0K:
    min : 5200
    max: 5320
    nbins: 100
    var_signal: "(B_M-D1_M-D2_M+1.86484*2)*1000"
    var: "(B_M_BK2pip-D1_M_BK2pip-D2_M_BK2pip+1.86484*2)*1000"
    cut: "D1K_ProbNNk_BK2pip>0.1 && D2K_ProbNNk_BK2pip>0.1 \
                 && D1H_ProbNNpi_BK2pip>0.05 && D2H_ProbNNpi_BK2pip>0.05 \
                 && BK_ProbNNpi_BK2pip>0.05 \
                 && D1H_ProbNNpi_BK2pip*(1-D1H_ProbNNk_BK2pip)>0.2 \
                 && D2H_ProbNNpi_BK2pip*(1-D2H_ProbNNk_BK2pip)>0.2 \
                 && BK_ProbNNpi_BK2pip*(1-BK_ProbNNk_BK2pip)>0.2 \
                 && D1_M>1.845 && D1_M<1.885 && D2_M>1.845 && D2_M<1.885"

B2DDK:
    min: 5200
    max: 5310
    nbins: 100
    var_signal: "(B_M-D1_M-D2_M+1.86966*2)*1000"
    var: "(B_M_BK2pip-D1_M_BK2pip-D2_M_BK2pip+1.86966*2)*1000"
    cut: "D1K_ProbNNk_BK2pip>0.1 && D2K_ProbNNk_BK2pip>0.1 \
                 && D1H_ProbNNpi_BK2pip>0.05 && D1h_ProbNNpi_BK2pip>0.05 \
                 && D2H_ProbNNpi_BK2pip>0.05 && D2h_ProbNNpi_BK2pip>0.05 \
                 && BK_ProbNNpi_BK2pip>0.05 \
                 && D1H_ProbNNpi_BK2pip*(1-D1H_ProbNNk_BK2pip)>0.2 \
                 && D1h_ProbNNpi_BK2pip*(1-D1h_ProbNNk_BK2pip)>0.2 \
                 && D2H_ProbNNpi_BK2pip*(1-D2H_ProbNNk_BK2pip)>0.2 \
                 && D2h_ProbNNpi_BK2pip*(1-D2h_ProbNNk_BK2pip)>0.2 \
                 && BK_ProbNNpi_BK2pip*(1-BK_ProbNNk_BK2pip)>0.2 \
                 && D1_M>1.850 && D1_M<1.890 && D2_M>1.850 && D2_M<1.890"

B2D0D0K2b4b:
    min: 5200
    max: 5310
    nbins: 100
    var_signal: "(B_M-D2b_M-D4b_M+1.86966*2)*1000"
    var: "(B_M_BK2pip-D2b_M_BK2pip-D4b_M_BK2pip+1.86966*2)*1000"
    cut: "D2bK_ProbNNk_BK2pip>0.1 && D4bK_ProbNNk_BK2pip>0.1 \
                 && D2bH_ProbNNpi_BK2pip>0.05 \
                 && D2bH_ProbNNpi_BK2pip>0.05 \
                 && BK_ProbNNpi_BK2pip>0.05 \
                 && D4bH_ProbNNpi_BK2pip*(1-D4bH_ProbNNk_BK2pip)>0.2 \
                 && D4bHp_ProbNNpi_BK2pip*(1-D4bHp_ProbNNk_BK2pip)>0.2 \
                 && D4bHm_ProbNNpi_BK2pip*(1-D4bHm_ProbNNk_BK2pip)>0.2 \
                 && BK_ProbNNpi_BK2pip*(1-BK_ProbNNk_BK2pip)>0.2 \
                 && D2b_M>1.850 && D2b_M<1.890 && D4b_M>1.850 && D4b_M<1.890"

B2D0D0K4b2b:
    min: 5200
    max: 5310
    nbins: 100
    var_signal: "(B_M-D2b_M-D4b_M+1.86966*2)*1000"
    var: "(B_M_BK2pip-D2b_M_BK2pip-D4b_M_BK2pip+1.86966*2)*1000"
    cut: "D2bK_ProbNNk_BK2pip>0.1 && D4bK_ProbNNk_BK2pip>0.1 \
                 && D2bH_ProbNNpi_BK2pip>0.05 \
                 && D2bH_ProbNNpi_BK2pip>0.05 \
                 && BK_ProbNNpi_BK2pip>0.05 \
                 && D4bH_ProbNNpi_BK2pip*(1-D4bH_ProbNNk_BK2pip)>0.2 \
                 && D4bHp_ProbNNpi_BK2pip*(1-D4bHp_ProbNNk_BK2pip)>0.2 \
                 && D4bHm_ProbNNpi_BK2pip*(1-D4bHm_ProbNNk_BK2pip)>0.2 \
                 && BK_ProbNNpi_BK2pip*(1-BK_ProbNNk_BK2pip)>0.2 \
                 && D2b_M>1.850 && D2b_M<1.890 && D4b_M>1.850 && D4b_M<1.890"
