B2DDK:
    min: 5200
    max: 5310
    nbins: 100
    var: "(B_M_BK2pip-D1_M_BK2pip-D2_M_BK2pip+1.86966*2)*1000"
    cut: "D1K_ProbNNk_BK2pip>0.1 && D2K_ProbNNk_BK2pip>0.1 \
                 && D1H_ProbNNpi_BK2pip>0.05 && D1h_ProbNNpi_BK2pip>0.05 \
                 && D2H_ProbNNpi_BK2pip>0.05 && D2h_ProbNNpi_BK2pip>0.05 \
                 && BK_ProbNNpi_BK2pip>0.05 \
                 && D1H_ProbNNpi_BK2pip*(1-D1H_ProbNNk_BK2pip)>0.2 \
                 && D1h_ProbNNpi_BK2pip*(1-D1h_ProbNNk_BK2pip)>0.2 \
                 && D2H_ProbNNpi_BK2pip*(1-D2H_ProbNNk_BK2pip)>0.2 \
                 && D2h_ProbNNpi_BK2pip*(1-D2h_ProbNNk_BK2pip)>0.2 \
                 && BK_ProbNNpi_BK2pip*(1-BK_ProbNNk_BK2pip)>0.2 \
                 && D1_M>1.850 && D1_M<1.890 && D2_M>1.850 && D2_M<1.890"


