B2D0D0bK:
    min : 5200
    max: 5320
    nbins: 100
    var_signal: "(B_M-D1_M-D2_M+1.86484*2)*1000"
    var: "(B_M_BK2pip-D1_M_BK2pip-D2_M_BK2pip+1.86484*2)*1000"
    cut: "D1K_ProbNNk_BK2pip>0.1 && D2K_ProbNNk_BK2pip>0.1 \
                 && D1H_ProbNNpi_BK2pip>0.05 && D2H_ProbNNpi_BK2pip>0.05 \
                 && BK_ProbNNpi_BK2pip>0.05 \
                 && D1H_ProbNNpi_BK2pip*(1-D1H_ProbNNk_BK2pip)>0.2 \
                 && D2H_ProbNNpi_BK2pip*(1-D2H_ProbNNk_BK2pip)>0.2 \
                 && BK_ProbNNpi_BK2pip*(1-BK_ProbNNk_BK2pip)>0.2 \
                 && D1_M>1.845 && D1_M<1.885 && D2_M>1.845 && D2_M<1.885"
